# Generated by Django 5.0.2 on 2024-05-28 16:45

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='last name')),
                ('sex', models.CharField(blank=True, max_length=255, null=True, verbose_name='sex')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='birthday')),
                ('userid', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='user id')),
                ('access_token', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='access token')),
                ('refresh_token', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='refresh token')),
                ('scope', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='scope')),
                ('expiration_date', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True, verbose_name='expiration date')),
                ('token_type', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='token_type')),
                ('getmeas_data', models.JSONField(blank=True, editable=False, null=True, verbose_name='getmeas data')),
                ('fitbit_code_verifier', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='fitbit_code_verifier')),
                ('fitbit_userid', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='user id')),
                ('fitbit_access_token', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='access token')),
                ('fitbit_refresh_token', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='refresh token')),
                ('fitbit_scope', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='scope')),
                ('fitbit_expiration_date', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True, verbose_name='expiration date')),
                ('fitbit_token_type', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='token_type')),
                ('fitbit_getmeas_data', models.JSONField(blank=True, editable=False, null=True, verbose_name='getmeas data')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
